name: 运行 main.py

on:
  push:
    branches: [ main ]  # 可以根据需要更改分支名

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新版本的 Ubuntu 运行环境

    steps:
    - uses: actions/checkout@v2  # 检出代码库
      
    - name: 设置 Python 环境
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 使用最新的 Python 3.x 版本
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装 requirements.txt 中列出的所有依赖
        
    - name: 运行 main.py
      run: python main.py  # 执行 main.py 脚本
